---

all:
  vars:
    ansible_user: root
    ansible_port: 22      
    ansible_become: yes 
    ansible_become_method: sudo  
  hosts:
  children:

    SITE-A:
      children:

        A-PRODUCTION-ENV:
          children:

            A-PROD-DBSERVERS:
              hosts:
                host1.mydomain.com:
                  ansible_host: <host1.ipaddress>
                host2.mydomain.com:
                  ansible_host: <host2.ipaddress>                    

            A-PROD-APPSERVERS:
              hosts:
                host3.mydomain.com:
                  ansible_host: <host3.ipaddress>
                host4.mydomain.com:
                  ansible_host: <host4.ipaddress> 

        A-STAGING-ENV:
          children:

            A-STAG-DEVSERVERS:
              hosts:
                host5.mydomain.com:
                  ansible_host: <host5.ipaddress>
                host6.mydomain.com:
                  ansible_host: <host6.ipaddress>

            A-STAG-TESTSERVERS:
              hosts:
                host7.mydomain.com:
                  ansible_host: <host7.ipaddress>
                host8.mydomain.com:
                  ansible_host: <host8.ipaddress>
    SITE-B:
      children:

        B-PRODUCTION-ENV:
          hosts:
            host5.mydomain.com:
              ansible_host: <host5.ipaddress>
            host6.mydomain.com:
              ansible_host: <host6.ipaddress>            

        B-STAGING-ENV:
          hosts:
            host7.mydomain.com:
              ansible_host: <host7.ipaddress>
            host8.mydomain.com:
              ansible_host: <host8.ipaddress>                  
